name: Compilability check
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        abi: [ "armeabi-v7a", "arm64-v8a", "x86", "x86_64" ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-${{ matrix.abi }}
          create-symlink: true

      - name: Setup the environment
        run: |
          sudo apt update
          sudo apt install -y meson nasm ninja-build

      - name: Executing FFmpeg Build
        run: |
          export ANDROID_SDK_HOME=$ANDROID_HOME
          export ANDROID_NDK_HOME=$ANDROID_NDK_LATEST_HOME
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          ./ffmpeg-android-maker.sh -all-free -all-gpl -android=24 -abis=${{ matrix.abi }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-binary-${{ matrix.abi }}
          path: ./output/lib/${{ matrix.abi }}
